version: '3.8'
services:
 dev-db:
  image: postgres:13
  ports:
   - 5434:5432
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: 123
   POSTGRES_DB: casinocats
  networks:
   - casinocatsworld
 dev-cache:
  image: redis
  ports:
   - 6379:6379
  networks:
   - casinocatsworld

networks:
 casinocatsworld:
